# Generated by Django 5.0.6 on 2024-07-04 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_default_image_alter_project_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='default_image',
        ),
    ]
