# Generated by Django 5.0.6 on 2024-06-07 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_expierence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_name',
            new_name='username',
        ),
    ]
