# Generated by Django 5.0.6 on 2024-06-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_user_name_profile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
