# Generated by Django 5.0.6 on 2024-05-27 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_skills_profile_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='expierence',
            field=models.TextField(blank=True),
        ),
    ]
